#!/usr/bin/env bash
#MISE description="Build the binary"
#MISE sources=["**/*.go"]
#MISE outputs=["dist/oasc_${GOOS}_${GOARCH}${EXT}"]

VERSION=${VERSION:-0.1.0}
BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
GIT_COMMIT=$(git rev-parse --short HEAD)

go build -ldflags="-X main.Version=$VERSION -X main.BuildTime=$BUILD_TIME -X main.GitCommit=$GIT_COMMIT" -o dist/oasc_${GOOS}_${GOARCH}${EXT} ./cmd/oasc
