#!/usr/bin/env bash
#MISE description="Build binaries for all platforms"
#MISE depends=["clean"]

VERSION=${VERSION} GOOS=darwin GOARCH=amd64 EXT= mise run build
VERSION=${VERSION} GOOS=darwin GOARCH=arm64 EXT= mise run build
VERSION=${VERSION} GOOS=linux GOARCH=amd64 EXT= mise run build
VERSION=${VERSION} GOOS=linux GOARCH=arm64 EXT= mise run build
VERSION=${VERSION} GOOS=windows GOARCH=amd64 EXT=.exe mise run build
